name: Main Github Actions
on:
  workflow_dispatch:
  push:
    branches:
      - main # (main branch) Set branch of the GH repo to push      
jobs:
  test_suite: # Name of the job
      runs-on: ubuntu-latest # Choosing OS
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0' # In command line run “node -v” and choose your version
      - run: npm ci
      # - run: npm config set script-shell "G:\Git\bin\bash.exe"
      - name: Install Cypress
        run: npx cypress install
      - name: run test
        run: npm run test # Our name of the headless script
      - name: Get Allure history
              uses: actions/checkout@v2
              if: always()
              continue-on-error: true
              with:
                  ref: allure
                  path: allure

            - name: Generate Allure Report
              uses: simple-elf/allure-report-action@master
              if: always()
              with:
                  allure_results: allure-results
                  gh_pages: allure
      - name: Upload Results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: allure-results
          path: ./allure-results # Name of the folder with allure results                    
      - name: Publishing Allure artifact to Github Actions
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure-report
          path: allure-report       
      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: always()
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: allure-report # The folder the action should deploy.
